[project]
name = "reservehub"
version = "0.1.0"
description = "Sistema de reservas con notificaciones"
requires-python = ">=3.11"
dependencies = [
    "aiofiles",
    "aiosqlite",
    "alembic",
    "amqp",
    "annotated-doc",
    "annotated-types",
    "anyio",
    "asyncpg",
    "bcrypt==4.0.1",
    "billiard",
    "celery",
    "cffi",
    "click",
    "click-didyoumean",
    "click-plugins",
    "click-repl",
    "colorama",
    "cryptography",
    "dnspython",
    "ecdsa",
    "email-validator",
    "fastapi",
    "greenlet",
    "h11",
    "httptools",
    "idna",
    "kombu",
    "mako",
    "markupsafe",
    "packaging",
    "passlib",
    "prompt-toolkit",
    "pyasn1",
    "pycparser",
    "pydantic",
    "pydantic-core",
    "pydantic-settings",
    "python-dateutil",
    "python-dotenv",
    "python-jose",
    "python-multipart",
    "pyyaml",
    "redis",
    "resend",
    "rsa",
    "six",
    "sqlalchemy",
    "starlette",
    "typing-extensions",
    "typing-inspection",
    "tzdata",
    "tzlocal",
    "uvicorn",
    "vine",
    "watchfiles",
    "wcwidth",
    "websockets",
]

[project.optional-dependencies]
dev = [
    "ast-serialize",
    "coverage",
    "httpcore",
    "httpx",
    "iniconfig",
    "librt",
    "mypy",
    "mypy-extensions",
    "pathspec",
    "pluggy",
    "pygments",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "ruff",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
pythonpath = ["."]